spring.application.name=OrderService
spring.profiles.active=test

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

internal.secret=super-secret-internal
internal.secret.header=X-Internal-Secret

spring.jackson.deserialization.use-big-decimal-for-floats=true
